env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: 'off'
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
  callback-return: error
  camelcase: error
  capitalized-comments: 'off'
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: error
  eqeqeq:
    - error
    - always
    - null: never
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  func-style: 'off'
  generator-star-spacing:
    - error
    - after
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing:
    - error
    - after: true
      before: true
  line-comment-position: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: 'off'
  lines-around-directive: error
  max-depth: error
  max-len: 'off'
  max-lines: 'off'
  max-nested-callbacks: error
  max-params:
    - error
    - 5
  max-statements: 'off'
  max-statements-per-line: error
  multiline-ternary:
    - error
    - never
  new-cap: 'off'
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-continue: 'off'
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: 'off'
  no-empty-function: error
  no-eq-null: 'off'
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign:
    - error
    - props: false
  no-path-concat: error
  no-plusplus: 'off'
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: 'off'
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: 'off'
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: 'off'
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: 'off'
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  object-shorthand:
    - error
    - properties
  one-var: 'off'
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-numeric-literals: error
  prefer-reflect: 'off'
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: 'off'
  quotes:
    - error
    - single
  radix: error
  require-await: error
  require-jsdoc: error
  rest-spread-spacing:
    - error
    - never
  semi: error
  semi-spacing: error
  sort-imports: 'off'
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  strict:
    - error
    - safe
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
